version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@0.0.10
  codecov: codecov/codecov@1.0.2
workflows:
  node-tests:
    jobs:
      - node/test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
  codecov-report:
    jobs:
      - codecov

jobs:
  codecov:
    steps:
    - checkout
    - run: npm install
    - run: npm run test-coverage
    - run: npm run codecov